type: tabular
name: MoleculeNet/BBBP
task: classification
modality: property
path: data/MoleculeNet/BBBP.csv
info:
  split_col: split
  split_method: scaffold
  split_fracs: [0.8, 0.1, 0.1]
  split_seed: 123
  smiles_col: smiles
  label_col: p_np
  id_col: num
  keep_invalid: True
out: runs/moleculenet
