type: tabular
name: MoleculeNet/ClinTox
task: classification
modality: property
path: data/MoleculeNet/ClinTox.csv
info:
  split_col: split
  smiles_col: smiles
  label_cols:
    - FDA_APPROVED
    - CT_TOX
  keep_invalid: True
out: runs/moleculenet
