type: tabular
name: MoleculeNet/FreeSolv
task: regression
modality: property
path: data/MoleculeNet/FreeSolv.csv
info:
  split_col: split
  split_method: random
  split_fracs: [0.8, 0.1, 0.1]
  split_seed: 123
  smiles_col: smiles
  label_col: expt
  id_col: iupac
  keep_invalid: True
out: runs/moleculenet
