type: tabular
name: MoleculeNet/HIV
task: classification
modality: property
path: data/MoleculeNet/HIV.csv
info:
  split_col: split
  split_method: scaffold
  split_fracs: [0.8, 0.1, 0.1]
  split_seed: 123
  smiles_col: smiles
  label_col: HIV_active
  id_col: activity
  keep_invalid: True
out: runs/moleculenet
