type: tabular
name: MoleculeNet/Lipophilicity
task: regression
modality: property
path: data/MoleculeNet/Lipophilicity.csv
info:
  split_col: split
  split_method: random
  split_fracs: [0.8, 0.1, 0.1]
  split_seed: 123
  smiles_col: smiles
  label_col: exp
  id_col: CMPD_CHEMBLID
  keep_invalid: True
out: runs/moleculenet
