type: tabular
name: MoleculeNet/Tox21
task: classification
modality: property
path: data/MoleculeNet/Tox21.csv
info:
  split_col: split
  split_method: random
  split_fracs: [0.8, 0.1, 0.1]
  split_seed: 123
  smiles_col: smiles
  label_cols:
    - NR-AR
    - NR-AR-LBD
    - NR-AhR
    - NR-Aromatase
    - NR-ER
    - NR-ER-LBD
    - NR-PPAR-gamma
    - SR-ARE
    - SR-ATAD5
    - SR-HSE
    - SR-MMP
    - SR-p53
  id_col: mol_id
  keep_invalid: True
out: runs/moleculenet
