type: dti
name: BioSNAP_scaffold_cls
task: classification
modality: dti
paths:
  train: data/BioSNAP/scaffold/train.csv
  valid: data/BioSNAP/scaffold/valid.csv
  test: data/BioSNAP/scaffold/test.csv
info:
  smiles_col: Ligand
  sequence_col: Protein
  label_col: classification_label
  keep_invalid: True
out: runs/dti
