type: dti
name: Human_random_cls
task: classification
modality: dti
paths:
  train: data/Human/random/train.csv
  valid: data/Human/random/valid.csv
  test: data/Human/random/test.csv
info:
  smiles_col: Ligand
  sequence_col: Protein
  label_col: classification_label
  keep_invalid: True
out: runs/dti
