type: dti
name: PDBBindv2016_reg
task: regression
modality: dti
paths:
  train: data/PDBBindv2016/train.csv
  valid: data/PDBBindv2016/valid.csv
  test: data/PDBBindv2016/test.csv
info:
  smiles_col: Ligand
  sequence_col: Protein
  target_id_col: Target_ID
  label_col: regression_label
  id_col: ID
  keep_invalid: True
  unique_sequences_jsonl: helpers/dti_unique_sequences.jsonl
  foldseek_m8_path: helpers/dti_all_vs_all.m8 #run the run_foldseek_fasta.sh script to generate this file
out: runs/dti
